# Project information

site_name: Protecting Workloads With AWS WAF, Amazon Inspector and AWS Systems Manager
site_description: This workshop shows how you can protect a web site using AWS Security Services
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://protecting-workloads.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/protecting-workloads-workshop'
repo_url: 'https://github.com/aws-samples/protecting-workloads-workshop'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: false
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra_javascript:
  - 'javascripts/extra.js'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
- Scenario: 'index.md'
- Getting Started: 'getting-started.md'
- Perimeter Layer:
  - 'Scenario': 'perimeter-layer/index.md'
  - 'Build Phase': 'perimeter-layer/build.md'
  - 'Assess Phase': 'perimeter-layer/assess.md'
  - 'Remediate Phase': 'perimeter-layer/remediate.md'
  - 'Verify Phase': 'perimeter-layer/verify.md'
  - 'Cleanup Phase': 'perimeter-layer/cleanup.md'
- Host Layer:
  - 'Scenario': 'host-layer/index.md'
  - 'Build Phase': 'host-layer/build.md'
  - 'Assess Phase': 'host-layer/assess.md'
  - 'Remediate Phase': 'host-layer/remediate.md'
  - 'Verify Phase': 'host-layer/verify.md'
  - 'Cleanup Phase': 'host-layer/cleanup.md'
- Cleanup: 'cleanup.md'
- Contributing: 'contribute.md'
- License: 'license.md'

