# Project information

site_name: Protecting Your Workloads
site_short_name: Protecting Your Workloads
site_description: This workshop shows how to implement protection measures for a web site using AWS WAF, AWS Inspector, and AWS Systems Manager.
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://protecting-workloads.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/protecting-workloads-workshop'
repo_url: 'https://github.com/aws-samples/protecting-workloads-workshop'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Home: 'index.md'
  - Getting Started: 'getting-started.md'
  - Build Phase: 'build.md'
  - Assess Phase: 'assess.md'
  - Remediate Phase: 'remediate.md'
  - Verify Phase: 'verify.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'
