# Project information

site_name: Security Workshops
site_description: 'A collection of AWS Security related workshops'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://awssecworkshops.com'

# Repository
repo_name: 'aws-samples/aws-security-workshops'
repo_url: 'https://github.com/aws-samples/aws-security-workshops'

# Copyright
copyright: '&copy; 2018, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra_javascript:
  - 'javascripts/extra.js'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Home: 'index.md'
  - Getting Started: 'getting-started.md'
  - Builder Sessions:
    - Directory: 'builder-sessions/index.md'
    - Permission Boundaries: 
      - Build Phase: 'builder-sessions/permission-boundary/build.md'
      - Verify Phase: 'builder-sessions/permission-boundary/verify.md'
  - Workshops: 
    - 'Directory': 'workshops/index.md'
    - 'Detection with Machine Learning': 'https://ml-threat-detection.awssecworkshops.com/'
    - 'Identity Round Robin': 
      - 'Overview': 'workshops/identity-round-robin/index.md'
      - 'Serverless Round':
        - 'Scenario': 'workshops/identity-round-robin/serverless/index.md'
        - 'Build Phase': 'workshops/identity-round-robin/serverless/build.md'
        - 'Verify Phase': 'workshops/identity-round-robin/serverless/verify.md'
      - 'Security Services Round':
        - 'Scenario': 'workshops/identity-round-robin/ess/index.md'
        - 'Build Phase': 'workshops/identity-round-robin/ess/build.md'
        - 'Verify Phase': 'workshops/identity-round-robin/ess/verify.md'
      - 'Permission Boundary Round':
        - 'Scenario': 'workshops/identity-round-robin/permission-boundaries/index.md'
        - 'Build Phase': 'workshops/identity-round-robin/permission-boundaries/build.md'
        - 'Verify Phase': 'workshops/identity-round-robin/permission-boundaries/verify.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'
