# Project information

site_name: Scalable, Automated Anomaly Detection with Amazon GuardDuty and SageMaker
site_short_name: Anomaly Detection with Amazon GuardDuty and SageMaker
site_description: This workshop shows how you can use an IP-based machine learning algorithm with Amazon SageMaker to augment and enrich findings from AWS Security services such as Amazon GuardDuty. You'll learn how to load the notebook in SageMaker, train the model, and score findings to determine abnormality of the activity.
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://scaling-threat-detection.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/aws-ml-detection-workshop'
repo_url: 'https://github.com/aws-samples/aws-ml-detection-workshop'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Workshop: 'index.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'
