# Project information

site_name: Protecting Workloads With AWS WAF, Amazon Inspector and AWS Systems Manager
site_description: This workshop shows how you can protect a web site using AWS Security Services
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://protecting-workloads.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/protecting-workloads-workshop'
repo_url: 'https://github.com/aws-samples/protecting-workloads-workshop'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: false
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra_javascript:
  - 'javascripts/extra.js'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
- Scenario: 'index.md'
- Getting Started: 'getting-started.md'
- Web Application Firewall:
  - 'Scenario': 'waf/index.md'
  - 'Build Phase': 'waf/build.md'
  - 'Assess Phase': 'waf/assess.md'
  - 'Remediate Phase': 'waf/remediate.md'
  - 'Verify Phase': 'waf/verify.md'
- Inspector and SM:
  - 'Scenario': 'inspector-sm/index.md'
  - 'Build Phase': 'inspector-sm/build.md'
  - 'Assess Phase': 'inspector-sm/assess.md'
  - 'Remediate Phase': 'inspector-sm/remediate.md'
  - 'Verify Phase': 'inspector-sm/verify.md'
- Cleanup: 'cleanup.md'
- Contributing: 'contribute.md'
- License: 'license.md'

